package org.totschnig.myexpenses.activity

const val CALCULATOR_REQUEST = 0
const val EDIT_REQUEST = 1
const val EDIT_ACCOUNT_REQUEST = 2
const val PREFERENCES_REQUEST = 3
const val CREATE_ACCOUNT_REQUEST = 4
const val FILTER_CATEGORY_REQUEST = 5
const val SELECT_CATEGORY_REQUEST = 7
const val IMPORT_FILENAME_REQUEST_CODE = 9
const val SYNC_BACKEND_SETUP_REQUEST = 10
const val RESTORE_REQUEST = 11
const val CONTRIB_REQUEST = 12
const val PLAN_REQUEST = 13
const val CONFIRM_DEVICE_CREDENTIALS_UNLOCK_REQUEST = 14
const val CONFIRM_DEVICE_CREDENTIALS_MANAGE_PROTECTION_SETTINGS_REQUEST = 15
const val PAYPAL_REQUEST = 16
const val INVOICE_REQUEST = 17
const val MAP_CATEGORY_REQUEST = 18
const val MAP_PAYEE_REQUEST = 19
const val MAP_METHOD_REQUEST = 20
const val MAP_ACCOUNT_REQUEST = 21
const val SELECT_TAGS_REQUEST = 22
const val FILTER_TAGS_REQUEST = 23
const val MAP_TAG_REQUEST = 24
const val CONFIRM_MAP_TAG_REQUEST = 25
const val FILTER_PAYEE_REQUEST = 26
const val OCR_REQUEST = 27