plugins {
    id 'com.android.dynamic-feature'
    id 'com.google.devtools.ksp'
}
android {
    compileSdk project.compileSdkVersion

    defaultConfig {
        missingDimensionStrategy 'textRecognition', 'extern'
        minSdk project.minSdkVersion
        resourceConfigurations = resConfig
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
    }

    lint {
        disable 'MissingTranslation'
    }

    namespace 'org.totschnig.webdav'
}

dependencies {
    implementation project(":myExpenses")
    implementation(libs.dav4android)
    implementation libs.androidx.appcompat
    implementation libs.okhttp
    ksp libs.dagger.compiler
    implementation libs.dagger
    testImplementation libs.junit
    testImplementation libs.truth
    androidTestImplementation project(":shared-test")
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.runner
}