#!/bin/bash

#copies the tutorial html from the app assets folder to a tutorial folder,
#and merges javascript needed into them
cd assets/tutorial
for i in tutorial*
do
	exec >../../tutorial/$i
	head -5 $i
	cat <<End-of-message
	<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/base/jquery-ui.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="images.js"></script>
End-of-message
	tail --lines=+6 $i
done

